// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/check_token": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "CheckToken 检查 CSRF Token 是否存在",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CSRF Token",
                        "name": "csrf",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login 账户登陆",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "账号",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "记住密码",
                        "name": "remember",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "tags": [
                    "Auth"
                ],
                "summary": "Logout 账户退出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/token": {
            "get": {
                "tags": [
                    "Auth"
                ],
                "summary": "Token 产生一个 CSRF Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/init": {
            "get": {
                "tags": [
                    "Home"
                ],
                "summary": "初始化接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "tags": [
                    "Session"
                ],
                "summary": "Session 信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Session 添加简介",
                "tags": [
                    "Session"
                ],
                "summary": "Session 添加",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Session"
                ],
                "summary": "Session 删除",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sessions/destory": {
            "delete": {
                "tags": [
                    "Session"
                ],
                "summary": "Session 销毁",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/todo": {
            "get": {
                "tags": [
                    "todo"
                ],
                "summary": "List 获取所有 Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数, 1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "当前页数, 默认20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Todo"
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "todo"
                ],
                "summary": "Update 更新单条或多条数据",
                "parameters": [
                    {
                        "type": "string",
                        "name": "date",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "name": "done",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "title",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Todo"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "todo"
                ],
                "summary": "Create 添加一条数据",
                "parameters": [
                    {
                        "type": "string",
                        "name": "date",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "name": "done",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "title",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Todo"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "todo"
                ],
                "summary": "Delete 删除单条或多条数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/todo/{id}": {
            "get": {
                "tags": [
                    "todo"
                ],
                "summary": "Detail 获取单条数据详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Todo"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "List 分页获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页数",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页记录",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create 添加一条数据",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "账号",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test",
                        "description": "姓名",
                        "name": "realname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "1",
                            "2",
                            "3"
                        ],
                        "type": "string",
                        "description": "所属组IDs",
                        "name": "groups",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test@gmail.com",
                        "description": "邮箱",
                        "name": "emali",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "状态",
                        "name": "status",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/user/createform": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "CreateForm 用户添加表单",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Form"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Detail 用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "账号ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "User"
                ],
                "summary": "Update 更新单条或多条数据",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "账号ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "default": "test",
                        "description": "账号",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test",
                        "description": "姓名",
                        "name": "realname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "1",
                            "2",
                            "3"
                        ],
                        "type": "string",
                        "description": "所属组IDs",
                        "name": "groups",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test@gmail.com",
                        "description": "邮箱",
                        "name": "emali",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "状态",
                        "name": "status",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            }
        },
        "/user{id}": {
            "delete": {
                "tags": [
                    "User"
                ],
                "summary": "Delete 删除单条或多条数据",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "账号ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Field": {
            "type": "object",
            "properties": {
                "field": {
                    "description": "字段",
                    "type": "string"
                },
                "label": {
                    "description": "标签",
                    "type": "string"
                },
                "rules": {
                    "description": "验证: required、numeric..., 详细看本页最下面",
                    "type": "string"
                },
                "tips": {
                    "description": "格式:bm://open:com.xxx.xxx",
                    "type": "string"
                },
                "type": {
                    "description": "类型: text、password、number、editor、textarea、file、image",
                    "type": "string"
                }
            }
        },
        "model.Form": {
            "type": "object",
            "properties": {
                "csrf": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Field"
                    }
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "model.Purview": {
            "description": "用户权限",
            "type": "object"
        },
        "model.Todo": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "done": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "description": "User account information",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像地址",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "groups": {
                    "description": "用户所属权限组",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "isFirstLogin": {
                    "description": "是否首次登录",
                    "type": "boolean"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "purviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Purview"
                    }
                },
                "realname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "sessionExpire": {
                    "description": "登录 Session 过期时间",
                    "type": "string"
                },
                "sessionID": {
                    "description": "登录 Session ID",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "uid": {
                    "description": "用户 ID",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Kaligo Example API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
