definitions:
  model.Todo:
    properties:
      date:
        type: string
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080/api
info:
  contact: {}
  title: Kaligo Example API
  version: "1.0"
paths:
  /sessions:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 删除
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
<<<<<<< HEAD
      summary: Session 信息
=======
      summary: Session 样例 Get
      tags:
      - session
>>>>>>> 643c8173ad82ecec031245d66cf6777830d0ccd7
    post:
      description: Session 添加简介
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
<<<<<<< HEAD
      summary: Session 添加
  /sessions/destory:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 销毁
=======
      summary: Session 样例 Set
      tags:
      - session
>>>>>>> 643c8173ad82ecec031245d66cf6777830d0ccd7
  /todo:
    delete:
      parameters:
      - description: Todo ID
        in: query
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Delete 删除单条或多条数据
      tags:
      - todo
    get:
      parameters:
      - description: 当前页数, 1开始
        in: query
        name: page
        type: integer
      - description: 当前页数, 默认20
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: 获取所有 Todo
      tags:
      - todo
    post:
      parameters:
      - in: formData
        name: date
        type: string
      - in: formData
        name: done
        type: boolean
      - in: formData
        name: id
        type: integer
      - in: formData
        name: title
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
      summary: Create 添加一条数据
      tags:
      - todo
    put:
      parameters:
      - in: formData
        name: date
        type: string
      - in: formData
        name: done
        type: boolean
      - in: formData
        name: id
        type: integer
      - in: formData
        name: title
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Update 更新单条或多条数据
      tags:
      - todo
  /todo/:id:
    get:
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
      summary: Detail 获取单条数据详情
      tags:
      - todo
swagger: "2.0"
