basePath: /api
definitions:
  model.Purview:
    type: object
  model.Todo:
    properties:
      date:
        type: string
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
  model.User:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      creatorId:
        type: integer
      deletedAt:
        type: string
      deletorId:
        type: integer
      email:
        type: string
      groups:
        items:
          type: integer
        type: array
      id:
        type: integer
      isFirstLogin:
        type: boolean
      password:
        type: string
      purviews:
        items:
          $ref: '#/definitions/model.Purview'
        type: array
      realname:
        type: string
      sessionExpire:
        type: string
      sessionID:
        type: string
      status:
        type: integer
      uid:
        type: string
      updatedAt:
        type: string
      updatorId:
        type: integer
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  title: Kaligo Example API
  version: "1.0"
paths:
  /init:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 初始化接口
      tags:
      - Home
  /sessions:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 删除
      tags:
      - Session
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 信息
      tags:
      - Session
    post:
      description: Session 添加简介
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 添加
      tags:
      - Session
  /sessions/destory:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 销毁
      tags:
      - Session
  /todo:
    delete:
      parameters:
      - description: Todo ID
        in: query
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Delete 删除单条或多条数据
      tags:
      - todo
    get:
      parameters:
      - description: 当前页数, 1开始
        in: query
        name: page
        type: integer
      - description: 当前页数, 默认20
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: List 获取所有 Todo
      tags:
      - todo
    post:
      parameters:
      - in: formData
        name: date
        type: string
      - in: formData
        name: done
        type: boolean
      - in: formData
        name: id
        type: integer
      - in: formData
        name: title
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
      summary: Create 添加一条数据
      tags:
      - todo
    put:
      parameters:
      - in: formData
        name: date
        type: string
      - in: formData
        name: done
        type: boolean
      - in: formData
        name: id
        type: integer
      - in: formData
        name: title
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Update 更新单条或多条数据
      tags:
      - todo
  /todo/{id}:
    get:
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
      summary: Detail 获取单条数据详情
      tags:
      - todo
  /user:
    delete:
      parameters:
      - default: 1
        description: 账号ID
        in: path
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Delete 删除单条或多条数据
      tags:
      - User
    get:
      parameters:
      - default: 1
        description: 当前页数
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页记录
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: List 分页获取用户信息
      tags:
      - User
    post:
      parameters:
      - default: test
        description: 账号
        in: formData
        name: username
        required: true
        type: string
      - default: test
        description: 密码
        in: formData
        name: password
        required: true
        type: string
      - default: test
        description: 姓名
        in: formData
        name: realname
        required: true
        type: string
      - description: 所属组IDs
        enum:
        - "1"
        - "2"
        - "3"
        in: formData
        name: groups
        required: true
        type: string
      - default: test@gmail.com
        description: 邮箱
        in: formData
        name: emali
        type: string
      - default: 1
        description: 状态
        in: formData
        name: status
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Create 添加一条数据
      tags:
      - User
    put:
      parameters:
      - default: 1
        description: 账号ID
        in: path
        name: id
        type: integer
      - default: test
        description: 账号
        in: formData
        name: username
        required: true
        type: string
      - default: test
        description: 密码
        in: formData
        name: password
        required: true
        type: string
      - default: test
        description: 姓名
        in: formData
        name: realname
        required: true
        type: string
      - description: 所属组IDs
        enum:
        - "1"
        - "2"
        - "3"
        in: formData
        name: groups
        required: true
        type: string
      - default: test@gmail.com
        description: 邮箱
        in: formData
        name: emali
        type: string
      - default: 1
        description: 状态
        in: formData
        name: status
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Update 更新单条或多条数据
      tags:
      - User
  /user/{id}:
    get:
      parameters:
      - default: 1
        description: 账号ID
        in: path
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Detail 用户信息
      tags:
      - User
  /user/login:
    post:
      parameters:
      - default: test
        description: 账号
        in: formData
        name: username
        required: true
        type: string
      - default: test
        description: 密码
        in: formData
        name: password
        required: true
        type: string
      - default: true
        description: 记住密码
        in: formData
        name: remember
        required: true
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login 账户登陆
      tags:
      - User
  /user/logout:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout 账户退出
      tags:
      - User
swagger: "2.0"
