basePath: /api
definitions:
  model.Component:
    properties:
      field:
        description: 字段
        type: string
      placeholder:
        description: 输入框占位文本
        type: string
      props:
        $ref: '#/definitions/model.Props'
        description: 属性
      tips:
        description: 格式:bm://open:com.xxx.xxx
        type: string
      title:
        description: 标题
        type: string
      type:
        description: '类型: input、editor、textarea、file、image'
        type: string
      validate:
        $ref: '#/definitions/model.Validate'
        description: '验证: required、numeric..., 详细看本页最下面'
      value:
        description: 默认值
        type: string
    type: object
  model.Form:
    properties:
      components:
        description: 表单组件
        items:
          $ref: '#/definitions/model.Component'
        type: array
      csrf:
        type: string
      method:
        type: string
      name:
        type: string
      path:
        type: string
    type: object
  model.Props:
    properties:
      type:
        description: '类型: text、password'
        type: string
    type: object
  model.Purview:
    description: 用户权限
    type: object
  model.User:
    description: User account information
    properties:
      avatar:
        description: 用户头像地址
        type: string
      email:
        description: 邮箱地址
        type: string
      first_login:
        description: 是否首次登录
        type: boolean
      groups:
        description: 用户所属权限组
        items:
          type: integer
        type: array
      id:
        description: 用户ID
        type: integer
      purviews:
        items:
          $ref: '#/definitions/model.Purview'
        type: array
      realname:
        description: 用户昵称
        type: string
      status:
        description: 状态
        type: integer
      uid:
        description: UID
        type: string
      username:
        description: 用户名
        type: string
    required:
    - username
    type: object
  model.Validate:
    properties:
      enum:
        description: 枚举类型
        type: string
      len:
        description: 字段长度
        type: integer
      max:
        description: 最大长度
        type: integer
      message:
        description: 校验文案
        type: string
      min:
        description: 最小长度
        type: integer
      pattern:
        description: 正则表达式校验
        type: string
      required:
        description: 是否必选
        type: boolean
      type:
        description: '内建校验类型: date、datetimerange、emali、array'
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Kaligo Example API
  version: "1.0"
paths:
  /auth/check_token:
    post:
      parameters:
      - description: CSRF Token
        in: formData
        name: csrf
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: CheckToken 检查 CSRF Token 是否存在
      tags:
      - Auth
  /auth/login:
    post:
      parameters:
      - default: test
        description: 账号
        in: formData
        name: username
        required: true
        type: string
      - default: test
        description: 密码
        in: formData
        name: password
        required: true
        type: string
      - default: true
        description: 记住密码
        in: formData
        name: remember
        required: true
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login 账户登陆
      tags:
      - Auth
  /auth/logout:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout 账户退出
      tags:
      - Auth
  /auth/token:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Token 产生一个 CSRF Token
      tags:
      - Auth
  /init:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 初始化接口
      tags:
      - Home
  /permissions:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: '权限列表: 权限选择、权限展示'
      tags:
      - Home
  /sessions:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 删除
      tags:
      - Session
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 信息
      tags:
      - Session
    post:
      description: Session 添加简介
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 添加
      tags:
      - Session
  /sessions/destory:
    delete:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Session 销毁
      tags:
      - Session
  /user:
    get:
      parameters:
      - default: 1
        description: 当前页数
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页记录
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: List 分页获取用户信息
      tags:
      - User
    post:
      parameters:
      - default: test
        description: 账号
        in: formData
        name: username
        required: true
        type: string
      - default: test
        description: 密码
        in: formData
        name: password
        required: true
        type: string
      - default: test
        description: 姓名
        in: formData
        name: realname
        required: true
        type: string
      - description: 所属组IDs
        enum:
        - "1"
        - "2"
        - "3"
        in: formData
        name: groups
        required: true
        type: string
      - default: test@gmail.com
        description: 邮箱
        in: formData
        name: emali
        type: string
      - default: 1
        description: 状态
        in: formData
        name: status
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Create 添加一条数据
      tags:
      - User
  /user/{id}:
    get:
      parameters:
      - default: 1
        description: 账号ID
        in: path
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Detail 用户信息
      tags:
      - User
    put:
      parameters:
      - default: 1
        description: 账号ID
        in: path
        name: id
        type: integer
      - default: test
        description: 账号
        in: formData
        name: username
        required: true
        type: string
      - default: test
        description: 密码
        in: formData
        name: password
        required: true
        type: string
      - default: test
        description: 姓名
        in: formData
        name: realname
        required: true
        type: string
      - description: 所属组IDs
        enum:
        - "1"
        - "2"
        - "3"
        in: formData
        name: groups
        required: true
        type: string
      - default: test@gmail.com
        description: 邮箱
        in: formData
        name: emali
        type: string
      - default: 1
        description: 状态
        in: formData
        name: status
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Update 更新单条或多条数据
      tags:
      - User
  /user/createform:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Form'
      summary: CreateForm 用户添加表单
      tags:
      - User
  /user{id}:
    delete:
      parameters:
      - default: 1
        description: 账号ID
        in: path
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Delete 删除单条或多条数据
      tags:
      - User
swagger: "2.0"
