server:
  host: 127.0.0.1
  port: 8080
websocket:
  host: 127.0.0.1
  port: 9527
database:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    pass: root
    name: kaligo
cache:
  config:
    driver: memory